export DB_PORT="5431"
export DB_USERNAME="emmanuel"
export DB_PASSWORD=""
export DB_HOST="127.0.0.1"
export DB_DATABASE="fpl"
export DB_DRIVER_NAME="postgresql+psycopg2"
export DJANGO_SECRET_KEY="django-insecure-f&xs472(b!o6_b$5l*--ea1*m^*_=y))edubhvkol3t4%2*#a_"
export REDIS_HOST="127.0.0.1"
export REDIS_PORT="6379"
# export REDIS_PASSWORD=None