name: Backend Deployment
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Deploy Backend Image'
        default: 'Deploy Backend Image'
        required: true
        type: string

env:
  PROJECT_NAME: fpl-analysis-tool
  ARTIFACT_REPO_NAME: fpl
  IMAGE_NAME: fpl-backend
  REVISION: poetry-dep
  REGION: europe-west2
  SERVICE_NAME: redeployed-backend

jobs: 
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
      
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v4'
        with: 
          ref: docker-production-sqlite

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "LiveProject/.python-version"

      - name: Create virtualenv
        run: |
          which python
          python -m venv venv
          source venv/bin/activate
          pipx install poetry
          cd LiveProject
          poetry install --no-root

      - name: Create cors.json
        run: |
          cat > cors.json <<'EOF'
          [
            {
              "origin": [
                "https://wrappedfrontend.web.app",
                "https://wrappedfrontend.firebaseapp.com",
                "https://fplwrapped.com"
              ],
              "method": ["GET", "HEAD", "POST"],
              "responseHeader": ["Content-Type", "Authorization"],
              "maxAgeSeconds": 3600
            }
          ]
          EOF

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: '${{secrets.WORKLOAD_IDENTITY_PROVIDERS }}'
          service_account: '${{ secrets.AUTH_SERVICE_ACCOUNT }}'
          run: gsutil cors set cors.json gs://2024_2025 gs://2025_2026

      - name: 'Docker auth'
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 'Build and push container'
        id: build
        run: |
          cd LiveProject
          docker build . -t ${{ env.IMAGE_NAME }}:${{ env.REVISION }} --no-cache
          docker tag ${{ env.IMAGE_NAME }}:${{ env.REVISION }} ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_NAME }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.REVISION }}
          echo "pushing ${{ env.REGION}}-docker.pkg.dev/${{ env.PROJECT_NAME }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.REVISION }} to Artifacts Registry"
          digest=$(docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_NAME }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.REVISION }} | grep -oP 'digest:\s*\K(sha256:[0-9a-f]+)')
          echo "Image pushed with digest: $digest"
          echo "digest=$digest" >> "$GITHUB_OUTPUT"
