name: Backend Deployment
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Deploy Backend Image'
        default: 'Deploy Backend Image'
        required: true
        type: string

env:
  PROJECT_NAME: fpl-analysis-tool
  ARTIFACT_REPO_NAME: fpl
  IMAGE_NAME: fpl-backend
  REVISION: GW38_entrypoint_gunicorn
  REGION: europe-west2

jobs: 
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
      
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v4'
        with: 
          ref: docker-production-sqlite

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "LiveProject/.python-version"

      - name: Create virtualenv
        run: |
          which python
          python -m venv venv
          source venv/bin/activate
          pip install -r LiveProject/requirements.txt
          which python
    
      - name: 'Update DB and info' # depends on endpoint
        run: |
            source venv/bin/activate
            # source init_env.sh
            # source startup.sh # should be standalone job for when container restarts

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: '${{secrets.WORKLOAD_IDENTITY_PROVIDERS }}'
          service_account: '${{ secrets.AUTH_SERVICE_ACCOUNT }}'
          process_gcloudignore: false

      - name: 'Docker auth'
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 'Build and push container'
        run: |
          cd LiveProject
          docker build . -t ${{ env.IMAGE_NAME }}:${{ env.REVISION }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.REVISION }} ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_NAME }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.REVISION }}
          echo "pushing ${{ env.REGION-docker.pkg.dev }}/${{ env.PROJECT_NAME }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.REVISION }} to Artifacts Registry"
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_NAME }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ env.REVISION }}
          echo "Image pushed"

