name: Fixtures & Gameweek
on:
  schedule:
    - cron: "0/10 20-22 * * 5"
    - cron: "0/10 12-20 * * 6"
    - cron: "0/10 14-20 * * 0"
        
  push:
    paths:
      - '.github/workflows/fixbuild.yml' 
  workflow_dispatch:
    inputs:
      name:
        description: 'Update Fixtures/Result'
        default: 'Update Fixtures/Result'
        required: true
        type: string

jobs:
  fixtures:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
      
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v4'
        with: 
          ref: develop

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "LiveProject/.python-version"

      - name: Create virtualenv
        run: |
          which python
          python -m venv venv
          source venv/bin/activate
          pipx install poetry
          cd LiveProject
          poetry install --no-root
          which python

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: '${{secrets.WORKLOAD_IDENTITY_PROVIDERS }}'
          service_account: '${{ secrets.AUTH_SERVICE_ACCOUNT }}'
          process_gcloudignore: false
    
      - name: 'Upload Fixtures'
        run: |
            source venv/bin/activate
            source init_env.sh
            cd LiveProject
            echo updating fixtures
            python src/db/update_season_fixture.py
            python src/gameview.py -f True -u True
            
      - name: 'Create Gameweek Report'
        run: |
            source venv/bin/activate
            source init_env.sh
            cd LiveProject
            echo ${{ env.GW }} report
            python src/db/update_player_information.py -ha 1
            python src/db/update_player_information.py -ha 2
            python src/db/update_gameweek_score.py -g ${{ secrets.GW }}
            python src/gameview.py -g ${{ secrets.GW }} -u True
