# This is a basic workflow that is manually triggered

name: GW13

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule: 
    - cron:  '15 6 * * *'
    
  workflow_dispatch:
    inputs:
      name:
        description: 'Endpoint to Scrap'
        default: 'Scrap Participants Entry'
        required: true
        type: string
env:
      GW: 13
      START: 1500000
      END: 1700000

jobs:
  scrap-and-upload:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
      
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v4'
        with: 
          ref: docker-production-sqlite

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "LiveProject/.python-version"

      - name: Create virtualenv
        run: |
          which python
          python -m venv venv
          source venv/bin/activate
          pip install -r LiveProject/requirements.txt
          which python

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: '${{secrets.WORKLOAD_IDENTITY_PROVIDERS }}'
          service_account: '${{ secrets.AUTH_SERVICE_ACCOUNT }}'
          process_gcloudignore: false
    
      - name: 'Scrap Weekly Entry'
        run: |
            source venv/bin/activate
            source init_env.sh
            cd LiveProject
            echo ${{ env.START }}.json
            touch  ${{ env.START }}.json
            echo ${{ github.event.schedule }}
            python src/db/write_participant_weekly_entry.py -g $GW -t 1 -s $START -e $END
