# This is a basic workflow that is manually triggered

name: GW5

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule: 
    - cron:  '15 22 * * *'
    
  workflow_dispatch:
    inputs:
      name:
        description: 'Endpoint to Scrap'
        default: 'Scrap Participants Entry'
        required: true
        type: string
env:
      GW: 5
      START: 1
      END: 100000

jobs:
  scrap:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
      
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v4'
        with: 
          ref: docker-production-sqlite

      
      - name: "update start & end"
        if: ${{ github.event.schedule == '* 18 * * *' }}
        run: |
          START=100000
          END=300000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV
          
      - name: "update start & end"
        if: ${{ github.event.schedule == '* 19 * * *' }}
        run: |
          START=300000
          END=500000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV
          
      - name: "update start & end"
        if: ${{ github.event.schedule == '* 20 * * *' }}
        run: |
          START=500000
          END=700000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV

      - name: "update start & end"
        if: ${{ github.event.schedule == '* 21 * * *' }}
        run: |
          START=700000
          END=900000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV

      - name: "update start & end"
        if: ${{ github.event.schedule == '* 22 * * *' }}
        run: |
          START=900000
          END=1100000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV

      - name: "update start & end"
        if: ${{ github.event.schedule == '* 23 * * *' }}
        run: |
          START=1100000
          END=1300000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV
          
      - name: "update start & end"
        if: ${{ github.event.schedule == '* 0 * * *' }}
        run: |
          START=1300000
          END=1500000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV
          
      - name: "update start & end"
        if: ${{ github.event.schedule == '* 1 * * *' }}
        run: |
          START=1500000
          END=1700000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV

      - name: "update start & end"
        if: ${{ github.event.schedule == '* 2 * * *' }}
        run: |
          START=1700000
          END=1900000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV

      - name: "update start & end"
        if: ${{ github.event.schedule == '* 3 * * *' }}
        run: |
          START=1900000
          END=2100000
          echo START=$START >> $GITHUB_ENV
          echo END=$END >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "LiveProject/.python-version"

      - name: Create virtualenv
        run: |
          which python
          python -m venv venv
          source venv/bin/activate
          pip install -r LiveProject/requirements.txt
          which python
    
      - name: 'Scrap Weekly Entry'
        run: |
            source venv/bin/activate
            source init_env.sh
            cd LiveProject
            echo ${{ env.START }}.json
            touch  ${{ env.START }}.json
            echo ${{ github.event.schedule }}
            python src/db/write_participant_weekly_entry.py -g $GW -t 1 -s $START -e $END > ${{ env.START }}.json
      # make dynamic

      - name: 'Upload scrapped weekly entry'
        uses: actions/upload-artifact@v4
        with:
          name: weekly_entry
          path: LiveProject/${{ env.START }}.json

  upload:
    # Allow the job to fetch a GitHub ID token
      needs: scrap
      permissions:
        id-token: write
        contents: read
  
      runs-on: ubuntu-latest
      steps: 
        - id: 'checkout'
          uses: 'actions/checkout@v4'
          
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v2'
          with:
            create_credentials_file: true
            workload_identity_provider: '${{secrets.WORKLOAD_IDENTITY_PROVIDERS }}'
            service_account: '${{ secrets.AUTH_SERVICE_ACCOUNT }}'
            process_gcloudignore: false

        - name: Download outputted json
          uses: actions/download-artifact@v4
          with:
            name: weekly_entry
            path: LiveProject/${{ env.START }}.json
            
        - id: 'upload-folder'
          uses: 'google-github-actions/upload-cloud-storage@v2'
          with:
            path: LiveProject/${{ env.GW }}.json # modularize
            destination: 'wrapped_participants_entry'
    
