name : CI

on :
  push:
    paths:
      - 'LiveProject/**' 

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
  
  
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "LiveProject/.python-version"
              
      - name : load dependencies
        id: init_env
        run: python3 -m venv env | pip install -r LiveProject/requirements.txt

      - name : Run tests with pytest
        run: |
          source init_env.sh 
          source env/bin/activate
          cd LiveProject
          echo "Running Tests"
          pytest --cov src/ --cov-fail-under=80


